// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockdataresponse

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ErrorBuilder is an autogenerated mock type for the ErrorBuilder type
type ErrorBuilder struct {
	mock.Mock
}

type ErrorBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorBuilder) EXPECT() *ErrorBuilder_Expecter {
	return &ErrorBuilder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, status, message, details
func (_m *ErrorBuilder) Execute(ctx context.Context, status int, message string, details any) any {
	ret := _m.Called(ctx, status, message, details)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(context.Context, int, string, any) any); ok {
		r0 = rf(ctx, status, message, details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// ErrorBuilder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorBuilder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - status int
//   - message string
//   - details any
func (_e *ErrorBuilder_Expecter) Execute(ctx interface{}, status interface{}, message interface{}, details interface{}) *ErrorBuilder_Execute_Call {
	return &ErrorBuilder_Execute_Call{Call: _e.mock.On("Execute", ctx, status, message, details)}
}

func (_c *ErrorBuilder_Execute_Call) Run(run func(ctx context.Context, status int, message string, details any)) *ErrorBuilder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(any))
	})
	return _c
}

func (_c *ErrorBuilder_Execute_Call) Return(_a0 any) *ErrorBuilder_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorBuilder_Execute_Call) RunAndReturn(run func(context.Context, int, string, any) any) *ErrorBuilder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorBuilder creates a new instance of ErrorBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorBuilder {
	mock := &ErrorBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
