// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockdataresponse

import (
	http "net/http"

	dataresponse "github.com/raoptimus/data-response.go/v2"

	mock "github.com/stretchr/testify/mock"

	response "github.com/raoptimus/data-response.go/v2/response"
)

// HandlerFunc is an autogenerated mock type for the HandlerFunc type
type HandlerFunc struct {
	mock.Mock
}

type HandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerFunc) EXPECT() *HandlerFunc_Expecter {
	return &HandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: r, f
func (_m *HandlerFunc) Execute(r *http.Request, f *dataresponse.Factory) *response.DataResponse {
	ret := _m.Called(r, f)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *response.DataResponse
	if rf, ok := ret.Get(0).(func(*http.Request, *dataresponse.Factory) *response.DataResponse); ok {
		r0 = rf(r, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.DataResponse)
		}
	}

	return r0
}

// HandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type HandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - r *http.Request
//   - f *dataresponse.Factory
func (_e *HandlerFunc_Expecter) Execute(r interface{}, f interface{}) *HandlerFunc_Execute_Call {
	return &HandlerFunc_Execute_Call{Call: _e.mock.On("Execute", r, f)}
}

func (_c *HandlerFunc_Execute_Call) Run(run func(r *http.Request, f *dataresponse.Factory)) *HandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(*dataresponse.Factory))
	})
	return _c
}

func (_c *HandlerFunc_Execute_Call) Return(_a0 *response.DataResponse) *HandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerFunc_Execute_Call) RunAndReturn(run func(*http.Request, *dataresponse.Factory) *response.DataResponse) *HandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandlerFunc creates a new instance of HandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerFunc {
	mock := &HandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
