// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockdataresponse

import (
	http "net/http"

	dataresponse "github.com/raoptimus/data-response.go/v2"

	mock "github.com/stretchr/testify/mock"

	response "github.com/raoptimus/data-response.go/v2/response"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: r, f
func (_m *Handler) Handle(r *http.Request, f *dataresponse.Factory) *response.DataResponse {
	ret := _m.Called(r, f)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *response.DataResponse
	if rf, ok := ret.Get(0).(func(*http.Request, *dataresponse.Factory) *response.DataResponse); ok {
		r0 = rf(r, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.DataResponse)
		}
	}

	return r0
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - r *http.Request
//   - f *dataresponse.Factory
func (_e *Handler_Expecter) Handle(r interface{}, f interface{}) *Handler_Handle_Call {
	return &Handler_Handle_Call{Call: _e.mock.On("Handle", r, f)}
}

func (_c *Handler_Handle_Call) Run(run func(r *http.Request, f *dataresponse.Factory)) *Handler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(*dataresponse.Factory))
	})
	return _c
}

func (_c *Handler_Handle_Call) Return(_a0 *response.DataResponse) *Handler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Handle_Call) RunAndReturn(run func(*http.Request, *dataresponse.Factory) *response.DataResponse) *Handler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
