// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockdataresponse

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ValidationErrorBuilder is an autogenerated mock type for the ValidationErrorBuilder type
type ValidationErrorBuilder struct {
	mock.Mock
}

type ValidationErrorBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidationErrorBuilder) EXPECT() *ValidationErrorBuilder_Expecter {
	return &ValidationErrorBuilder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, message, attributeErrors
func (_m *ValidationErrorBuilder) Execute(ctx context.Context, message string, attributeErrors map[string][]string) any {
	ret := _m.Called(ctx, message, attributeErrors)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string][]string) any); ok {
		r0 = rf(ctx, message, attributeErrors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// ValidationErrorBuilder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ValidationErrorBuilder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - attributeErrors map[string][]string
func (_e *ValidationErrorBuilder_Expecter) Execute(ctx interface{}, message interface{}, attributeErrors interface{}) *ValidationErrorBuilder_Execute_Call {
	return &ValidationErrorBuilder_Execute_Call{Call: _e.mock.On("Execute", ctx, message, attributeErrors)}
}

func (_c *ValidationErrorBuilder_Execute_Call) Run(run func(ctx context.Context, message string, attributeErrors map[string][]string)) *ValidationErrorBuilder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string][]string))
	})
	return _c
}

func (_c *ValidationErrorBuilder_Execute_Call) Return(_a0 any) *ValidationErrorBuilder_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ValidationErrorBuilder_Execute_Call) RunAndReturn(run func(context.Context, string, map[string][]string) any) *ValidationErrorBuilder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidationErrorBuilder creates a new instance of ValidationErrorBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidationErrorBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidationErrorBuilder {
	mock := &ValidationErrorBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
