// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockmiddleware

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ContextValueFunc is an autogenerated mock type for the ContextValueFunc type
type ContextValueFunc struct {
	mock.Mock
}

type ContextValueFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextValueFunc) EXPECT() *ContextValueFunc_Expecter {
	return &ContextValueFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ContextValueFunc) Execute(ctx context.Context) interface{} {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ContextValueFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ContextValueFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ContextValueFunc_Expecter) Execute(ctx interface{}) *ContextValueFunc_Execute_Call {
	return &ContextValueFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ContextValueFunc_Execute_Call) Run(run func(ctx context.Context)) *ContextValueFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ContextValueFunc_Execute_Call) Return(_a0 interface{}) *ContextValueFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextValueFunc_Execute_Call) RunAndReturn(run func(context.Context) interface{}) *ContextValueFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewContextValueFunc creates a new instance of ContextValueFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextValueFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextValueFunc {
	mock := &ContextValueFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
