// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockmiddleware

import (
	middleware "github.com/raoptimus/data-response.go/v2/middleware"
	mock "github.com/stretchr/testify/mock"
)

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

type MetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsService) EXPECT() *MetricsService_Expecter {
	return &MetricsService_Expecter{mock: &_m.Mock}
}

// Responded provides a mock function with given fields: data
func (_m *MetricsService) Responded(data middleware.MetricsData) {
	_m.Called(data)
}

// MetricsService_Responded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Responded'
type MetricsService_Responded_Call struct {
	*mock.Call
}

// Responded is a helper method to define mock.On call
//   - data middleware.MetricsData
func (_e *MetricsService_Expecter) Responded(data interface{}) *MetricsService_Responded_Call {
	return &MetricsService_Responded_Call{Call: _e.mock.On("Responded", data)}
}

func (_c *MetricsService_Responded_Call) Run(run func(data middleware.MetricsData)) *MetricsService_Responded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(middleware.MetricsData))
	})
	return _c
}

func (_c *MetricsService_Responded_Call) Return() *MetricsService_Responded_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetricsService_Responded_Call) RunAndReturn(run func(middleware.MetricsData)) *MetricsService_Responded_Call {
	_c.Run(run)
	return _c
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
