// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockresponse

import (
	response "github.com/raoptimus/data-response.go/v2/response"
	mock "github.com/stretchr/testify/mock"
)

// Formatter is an autogenerated mock type for the Formatter type
type Formatter struct {
	mock.Mock
}

type Formatter_Expecter struct {
	mock *mock.Mock
}

func (_m *Formatter) EXPECT() *Formatter_Expecter {
	return &Formatter_Expecter{mock: &_m.Mock}
}

// CanFormatBinary provides a mock function with no fields
func (_m *Formatter) CanFormatBinary() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanFormatBinary")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Formatter_CanFormatBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanFormatBinary'
type Formatter_CanFormatBinary_Call struct {
	*mock.Call
}

// CanFormatBinary is a helper method to define mock.On call
func (_e *Formatter_Expecter) CanFormatBinary() *Formatter_CanFormatBinary_Call {
	return &Formatter_CanFormatBinary_Call{Call: _e.mock.On("CanFormatBinary")}
}

func (_c *Formatter_CanFormatBinary_Call) Run(run func()) *Formatter_CanFormatBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Formatter_CanFormatBinary_Call) Return(_a0 bool) *Formatter_CanFormatBinary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Formatter_CanFormatBinary_Call) RunAndReturn(run func() bool) *Formatter_CanFormatBinary_Call {
	_c.Call.Return(run)
	return _c
}

// ContentType provides a mock function with no fields
func (_m *Formatter) ContentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Formatter_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type Formatter_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *Formatter_Expecter) ContentType() *Formatter_ContentType_Call {
	return &Formatter_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *Formatter_ContentType_Call) Run(run func()) *Formatter_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Formatter_ContentType_Call) Return(_a0 string) *Formatter_ContentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Formatter_ContentType_Call) RunAndReturn(run func() string) *Formatter_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function with given fields: resp
func (_m *Formatter) Format(resp *response.DataResponse) (response.FormattedResponse, error) {
	ret := _m.Called(resp)

	if len(ret) == 0 {
		panic("no return value specified for Format")
	}

	var r0 response.FormattedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*response.DataResponse) (response.FormattedResponse, error)); ok {
		return rf(resp)
	}
	if rf, ok := ret.Get(0).(func(*response.DataResponse) response.FormattedResponse); ok {
		r0 = rf(resp)
	} else {
		r0 = ret.Get(0).(response.FormattedResponse)
	}

	if rf, ok := ret.Get(1).(func(*response.DataResponse) error); ok {
		r1 = rf(resp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Formatter_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type Formatter_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
//   - resp *response.DataResponse
func (_e *Formatter_Expecter) Format(resp interface{}) *Formatter_Format_Call {
	return &Formatter_Format_Call{Call: _e.mock.On("Format", resp)}
}

func (_c *Formatter_Format_Call) Run(run func(resp *response.DataResponse)) *Formatter_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*response.DataResponse))
	})
	return _c
}

func (_c *Formatter_Format_Call) Return(_a0 response.FormattedResponse, _a1 error) *Formatter_Format_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Formatter_Format_Call) RunAndReturn(run func(*response.DataResponse) (response.FormattedResponse, error)) *Formatter_Format_Call {
	_c.Call.Return(run)
	return _c
}

// NewFormatter creates a new instance of Formatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Formatter {
	mock := &Formatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
