// Code generated by mockery v2.15.0. DO NOT EDIT.

package middleware

import mock "github.com/stretchr/testify/mock"

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

// Responded provides a mock function with given fields: data
func (_m *MockMetricsService) Responded(data MetricsData) {
	_m.Called(data)
}

type mockConstructorTestingTNewMockMetricsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetricsService(t mockConstructorTestingTNewMockMetricsService) *MockMetricsService {
	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
