// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockhandler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LivenessService is an autogenerated mock type for the LivenessService type
type LivenessService struct {
	mock.Mock
}

type LivenessService_Expecter struct {
	mock *mock.Mock
}

func (_m *LivenessService) EXPECT() *LivenessService_Expecter {
	return &LivenessService_Expecter{mock: &_m.Mock}
}

// Alive provides a mock function with given fields: ctx
func (_m *LivenessService) Alive(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Alive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LivenessService_Alive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alive'
type LivenessService_Alive_Call struct {
	*mock.Call
}

// Alive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LivenessService_Expecter) Alive(ctx interface{}) *LivenessService_Alive_Call {
	return &LivenessService_Alive_Call{Call: _e.mock.On("Alive", ctx)}
}

func (_c *LivenessService_Alive_Call) Run(run func(ctx context.Context)) *LivenessService_Alive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LivenessService_Alive_Call) Return(_a0 error) *LivenessService_Alive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LivenessService_Alive_Call) RunAndReturn(run func(context.Context) error) *LivenessService_Alive_Call {
	_c.Call.Return(run)
	return _c
}

// NewLivenessService creates a new instance of LivenessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLivenessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LivenessService {
	mock := &LivenessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
